### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ghost** [karandesai-96/yolog#3]
This appears to be python 2 only...

**Comment by kdexd** [comment]
@stugots Thanks for pointing this out. I'll work it out for you, or let me know if you wish to do it and open a PR ?

**Comment by ghost** [comment]
I'll do that!

**Comment by kdexd** [comment]
Great ! Open up a PR and I'll be happy to merge it for you :smile:

**Comment by kdexd** [comment]
@stugots @kyleniemeyer @StreakyCobra
Please upgrade your versions to `0.2.2`. I hope it works. Feel free to reopen the issue if it doesn't . Cheers !

**Comment by StreakyCobra** [comment]
I confirm 0.2.2 works with Python 3

**Comment by kdexd** [comment]
Great, cheers ! :smile:
