### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by dimitrieh** [karandesai-96/yolog#4]
getting following error when trying out, installed by pip.. using wrong version of python?

```
Traceback (most recent call last):
  File "/usr/local/bin/yolog", line 7, in <module>
    from yolog.main import main
  File "/usr/local/lib/python3.5/site-packages/yolog/main.py", line 46
    print help_description
                         ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by kdexd** [comment]
@dimitrieh Yes, this lacks Python3 support right now. Issue #3 is open for that. Let me fix it today. :smile:

**Comment by dimitrieh** [comment]
@karandesai-96 gotya! thanks for the work! 😄

**Comment by kdexd** [comment]
@dimitrieh Please follow these steps to build it from source:

```
git clone https://www.github.com/karandesai-96/yolog
cd yolog
python setup.py install --force
```

Please see whether any error is present or not. Let me know if there is.

**Comment by dimitrieh** [comment]
works like a horse! I like the cleaner look and extra options!

![image](https://cloud.githubusercontent.com/assets/429659/16114788/6ec2af72-33c3-11e6-974b-c6d69bb0ca61.png)

**Comment by dimitrieh** [comment]
Will i have to deinstall this and install from pip again, if wanted to update via it? As now i need to know manually if there is an updated version no?

**Comment by kdexd** [comment]
Awesome ! I am planning to add more flexibility in future versions, this is a very early state. You may "Watch" this repository for getting updates.

> Will i have to deinstall this and install from pip again, if wanted to update via it? As now i need to know manually if there is an updated version no?

Yes, I was waiting for your reply, whether it works or not, as I only have Python 2.7 installed. I will quickly bump the version to `0.2.2` on pip. You can delete the local repository and reinstall it to get `0.2.2` and subsequent versions can be directly updated. Cheers ! :smile:

**Comment by dimitrieh** [comment]
cheers! and I will

**Comment by kdexd** [comment]
It is done, you can get `0.2.2` from PyPI.

**Comment by dimitrieh** [comment]
ha, not to much at home in this;) how would i go and uninstall the local repo? where is it?

**Comment by kdexd** [comment]
The path where you installed it - if you are using ubuntu, check out using `ls` command.

**Comment by dimitrieh** [comment]
oh wait, think i already got it with `which yolog`
