### ISSUE TITLE
Build needs dependency

### ISSUE THREAD

**Issue by Atrusberlin** [karandesai-96/yolog#8]
Hello,

I've tried to install the bleeding edge version, but I recieved an error:

```
$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
```

What I have to do?

Greeting Daniel

**Comment by Atrusberlin** [comment]
I'm using python 3.5

Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Dec  7 2015, 11:16:01)

**Comment by kdexd** [comment]
Hi, @Atrusberlin thanks for trying out **yolog**. This is an issue between version compatibility. This module `ConfigParser` was named as `configparser` in Python 3. You may use a try-except block there.

``` python
try:
    from ConfigParser import SafeConfigParser
except ImportError:
    from configparser import SafeConfigParser
```

I think this should work. If you make this change and open a PR, I'll be very happy to merge it. Cheers ! :smile:

**Comment by kdexd** [comment]
Hi @Atrusberlin ! You can pull from the latest `master` now and run the build. Feel free to reopen it if at all there is a problem related to this. Cheers !

@mangalutsav: Thanks for the fix ! :grin:

**Comment by Atrusberlin** [comment]
Hi Karandesai,

thx for the fast response. I will try it.

Best regards
